version: '3.8'
services:
    # web:
    #     build: .
    #     env_file: ./.env.docker
    #     volumes: 
    #         - .:/go/src/app
    #     ports:
    #         - $GO_LOCAL_PORT:$GO_DOCKER_PORT
    #     restart: on-failure
    #     depends_on: 
    #         mariadb:
    #             condition: service_healthy
    #     environment: 
    #         MYSQL_HOST: mariadb
    mariadb:
        image: mariadb
        env_file: ./.env.docker
        environment: 
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
            - ./sql/:/docker-entrypoint-initdb.d/
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8081:80
        environment:
            PMA_HOSTS: mariadb
volumes:
    mysql:
    mysql_config: